deployment:
  kind: Deployment
  replicas: 1

updateStrategy:
  type: Recreate
  rollingUpdate: null

api:
  dashboard: false

ingressClass:
  enabled: true
  isDefaultClass: false
  name: traefik

gateway:
  enabled: false

gatewayClass:
  enabled: false

providers:
  kubernetesCRD:
    enabled: false
  kubernetesIngress:
    enabled: true
    publishedService:
      enabled: false
  kubernetesGateway:
    enabled: false

ports:
  web:
    hostPort: 80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    hostPort: 443
    exposedPort: 8443
    expose:
      default: false

service:
  enabled: false

nodeSelector:
  kubernetes.io/hostname: k8s-echokey-control-plane

tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi
