apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  labels:
    {{- include "echokey.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  clusterIP: None
  selector:
    {{- include "echokey.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    {{- include "echokey.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  selector:
    {{- include "echokey.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
