apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  labels:
    {{- include "echokey.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.redis.persistence.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size | quote }}
