apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  namespace: echokey-dev
  labels:
    app.kubernetes.io/name: echokey
    app.kubernetes.io/instance: echokey-dev
    app.kubernetes.io/component: postgresql
    app.kubernetes.io/managed-by: kubectl
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: echokey
    app.kubernetes.io/instance: echokey-dev
    app.kubernetes.io/component: postgresql
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: echokey-dev
  labels:
    app.kubernetes.io/name: echokey
    app.kubernetes.io/instance: echokey-dev
    app.kubernetes.io/component: postgresql
    app.kubernetes.io/managed-by: kubectl
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: echokey
    app.kubernetes.io/instance: echokey-dev
    app.kubernetes.io/component: postgresql
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
