apiVersion: v1
kind: PersistentVolume
metadata:
  name: echokey-dev-uploads
  labels:
    app.kubernetes.io/name: echokey
    app.kubernetes.io/instance: echokey-dev
    app.kubernetes.io/component: uploads
    app.kubernetes.io/managed-by: kubectl
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: 172.21.0.1
    path: /
